from typing import List
import random
from app.models.tarot import TarotType, TarotCard

class TarotService:
    BASE_URL = "https://www.sacred-texts.com/tarot/pkt/img/"
    
    ALL_CARDS = {
        "0": TarotCard(
            id="0",
            name="愚者",
            name_en="The Fool",
            image_url=f"{BASE_URL}ar00.jpg",
            description="代表纯真、自发、自由、冒险精神",
            keywords=["开始", "冒险", "信任", "纯真"],
            analysis="当下是开启新旅程的时机，保持好奇心和开放的态度",
            affirmation="我勇于探索未知，相信生命中的每一步都是成长",
            type=TarotType.MAJOR
        ),
        "1": TarotCard(
            id="1",
            name="魔术师",
            name_en="The Magician",
            image_url=f"{BASE_URL}ar01.jpg",
            description="象征创造力、技能、意志力与专注",
            keywords=["创造", "技能", "意志", "专注"],
            analysis="你拥有实现目标所需的一切资源，保持专注",
            affirmation="我掌握着无限的创造力，能够实现我的愿望",
            type=TarotType.MAJOR
        ),
        "2": TarotCard(
            id="2",
            name="女祭司",
            name_en="The High Priestess",
            image_url=f"{BASE_URL}ar02.jpg",
            description="代表直觉、神秘、内在智慧",
            keywords=["直觉", "智慧", "神秘", "潜意识"],
            analysis="倾听内心的声音，相信你的直觉判断",
            affirmation="我信任我的直觉，它指引我走向真理",
            type=TarotType.MAJOR
        ),
        "3": TarotCard(
            id="3",
            name="女皇",
            name_en="The Empress",
            image_url=f"{BASE_URL}ar03.jpg",
            description="象征丰盛、创造力、母性、自然",
            keywords=["丰盛", "创造", "滋养", "和谐"],
            analysis="关注生活中的美好，让创造力自然流露",
            affirmation="我与生活的丰盛能量连接，创造美好",
            type=TarotType.MAJOR
        ),
        "4": TarotCard(
            id="4",
            name="皇帝",
            name_en="The Emperor",
            image_url=f"{BASE_URL}ar04.jpg",
            description="代表权威、稳定、领导力、秩序",
            keywords=["权威", "稳定", "规划", "控制"],
            analysis="建立稳固的基础，保持理性和秩序",
            affirmation="我有能力掌控局面，创造稳定和秩序",
            type=TarotType.MAJOR
        ),
        "5": TarotCard(
            id="5",
            name="教皇",
            name_en="The Hierophant",
            image_url=f"{BASE_URL}ar05.jpg",
            description="象征传统、教育、精神指引",
            keywords=["传统", "学习", "指导", "信仰"],
            analysis="寻求智慧指引，尊重传统价值",
            affirmation="我愿意学习和成长，接受生命的指引",
            type=TarotType.MAJOR
        ),
        "6": TarotCard(
            id="6",
            name="恋人",
            name_en="The Lovers",
            image_url=f"{BASE_URL}ar06.jpg",
            description="代表选择、和谐、关系、爱",
            keywords=["选择", "爱情", "和谐", "平衡"],
            analysis="面对重要选择，聆听内心的声音",
            affirmation="我选择爱与和谐，相信内心的指引",
            type=TarotType.MAJOR
        ),
        "7": TarotCard(
            id="7",
            name="战车",
            name_en="The Chariot",
            image_url=f"{BASE_URL}ar07.jpg",
            description="象征胜利、意志力、进取、控制",
            keywords=["胜利", "前进", "决心", "控制"],
            analysis="保持坚定的意志，朝着目标前进",
            affirmation="我充满决心和力量，必将达到目标",
            type=TarotType.MAJOR
        ),
        "8": TarotCard(
            id="8",
            name="力量",
            name_en="Strength",
            image_url=f"{BASE_URL}ar08.jpg",
            description="代表内在力量、勇气、耐心",
            keywords=["力量", "勇气", "耐心", "温和"],
            analysis="用温和的方式展现内在力量",
            affirmation="我拥有无限的内在力量和勇气",
            type=TarotType.MAJOR
        ),
        "9": TarotCard(
            id="9",
            name="隐士",
            name_en="The Hermit",
            image_url=f"{BASE_URL}ar09.jpg",
            description="象征独处、内省、智慧、指引",
            keywords=["独处", "反思", "指引", "智慧"],
            analysis="需要一些独处时间进行深入思考",
            affirmation="在独处中，我找到内在的智慧之光",
            type=TarotType.MAJOR
        ),
        "10": TarotCard(
            id="10",
            name="命运之轮",
            name_en="Wheel of Fortune",
            image_url=f"{BASE_URL}ar10.jpg",
            description="代表变化、机遇、命运、循环",
            keywords=["变化", "机遇", "命运", "转折"],
            analysis="生活正在转折点上，保持积极态度",
            affirmation="我欢迎生命中的变化，相信好运即将到来",
            type=TarotType.MAJOR
        ),
        "11": TarotCard(
            id="11",
            name="正义",
            name_en="Justice",
            image_url=f"{BASE_URL}ar11.jpg",
            description="象征公正、平衡、真理、因果",
            keywords=["公正", "平衡", "真理", "决定"],
            analysis="保持公正客观，权衡各方因素",
            affirmation="我的决定公正平衡，遵循内心的真理",
            type=TarotType.MAJOR
        ),
        "12": TarotCard(
            id="12",
            name="倒吊人",
            name_en="The Hanged Man",
            image_url=f"{BASE_URL}ar12.jpg",
            description="代表牺牲、放下、新视角、等待",
            keywords=["牺牲", "等待", "顿悟", "转换"],
            analysis="需要改变视角，接受当前的状态",
            affirmation="我愿意改变视角，在静止中获得智慧",
            type=TarotType.MAJOR
        ),
        "13": TarotCard(
            id="13",
            name="死神",
            name_en="Death",
            image_url=f"{BASE_URL}ar13.jpg",
            description="象征转变、结束、重生、释放",
            keywords=["转变", "结束", "重生", "蜕变"],
            analysis="是时候放下旧的，迎接新的转变",
            affirmation="我拥抱改变，相信新生命的力量",
            type=TarotType.MAJOR
        ),
        "14": TarotCard(
            id="14",
            name="节制",
            name_en="Temperance",
            image_url=f"{BASE_URL}ar14.jpg",
            description="代表平衡、和谐、调和、耐心",
            keywords=["平衡", "调和", "耐心", "中庸"],
            analysis="保持平和的心态，寻找生活的平衡",
            affirmation="我在对立中找到平衡，保持内心的和谐",
            type=TarotType.MAJOR
        ),
        "15": TarotCard(
            id="15",
            name="恶魔",
            name_en="The Devil",
            image_url=f"{BASE_URL}ar15.jpg",
            description="象征束缚、欲望、执着、物质",
            keywords=["束缚", "欲望", "执着", "诱惑"],
            analysis="警惕内在的执着和束缚，保持清醒",
            affirmation="我能够识别并超越内在的束缚",
            type=TarotType.MAJOR
        ),
        "16": TarotCard(
            id="16",
            name="高塔",
            name_en="The Tower",
            image_url=f"{BASE_URL}ar16.jpg",
            description="代表突变、崩塌、启示、解放",
            keywords=["突变", "动荡", "觉醒", "解放"],
            analysis="准备迎接突如其来的变化和启示",
            affirmation="我在动荡中看到新的可能和自由",
            type=TarotType.MAJOR
        ),
        "17": TarotCard(
            id="17",
            name="星星",
            name_en="The Star",
            image_url=f"{BASE_URL}ar17.jpg",
            description="象征希望、启发、宁静、指引",
            keywords=["希望", "信心", "指引", "治愈"],
            analysis="保持希望和信心，相信美好即将到来",
            affirmation="我充满希望和信心，跟随内心的光芒",
            type=TarotType.MAJOR
        ),
        "18": TarotCard(
            id="18",
            name="月亮",
            name_en="The Moon",
            image_url=f"{BASE_URL}ar18.jpg",
            description="代表直觉、幻想、恐惧、潜意识",
            keywords=["直觉", "幻想", "恐惧", "迷惑"],
            analysis="面对内心的恐惧，相信直觉的指引",
            affirmation="我有勇气面对未知，信任内在的指引",
            type=TarotType.MAJOR
        ),
        "19": TarotCard(
            id="19",
            name="太阳",
            name_en="The Sun",
            image_url=f"{BASE_URL}ar19.jpg",
            description="象征快乐、活力、成功、光明",
            keywords=["快乐", "活力", "成功", "光明"],
            analysis="充满活力和乐观，展现真实的自我",
            affirmation="我散发光明和喜悦，拥抱生命的美好",
            type=TarotType.MAJOR
        ),
        "20": TarotCard(
            id="20",
            name="审判",
            name_en="Judgement",
            image_url=f"{BASE_URL}ar20.jpg",
            description="代表觉醒、重生、召唤、评估",
            keywords=["觉醒", "重生", "召唤", "复苏"],
            analysis="聆听内在的召唤，准备迎接新生",
            affirmation="我回应生命的召唤，准备重新开始",
            type=TarotType.MAJOR
        ),
        "21": TarotCard(
            id="21",
            name="世界",
            name_en="The World",
            image_url=f"{BASE_URL}ar21.jpg",
            description="象征完成、圆满、整合、成就",
            keywords=["完成", "圆满", "成就", "统合"],
            analysis="一个阶段即将圆满完成，准备新的开始",
            affirmation="我感恩当下的圆满，拥抱生命的整体",
            type=TarotType.MAJOR
        ),
        # 权杖组（22-35）
        "22": TarotCard(
            id="22",
            name="权杖王牌",
            name_en="Ace of Wands",
            image_url=f"{BASE_URL}wapa.jpg",
            description="象征新的开始、创造力、灵感的火花",
            keywords=["创意", "开始", "灵感", "潜力"],
            analysis="新的创意或项目即将开始，充满无限可能",
            affirmation="我拥抱新的创意和机会，让灵感自由流动",
            type=TarotType.WANDS
        ),
        "23": TarotCard(
            id="23",
            name="权杖二",
            name_en="Two of Wands",
            image_url=f"{BASE_URL}wa02.jpg",
            description="代表规划、远见、选择方向",
            keywords=["规划", "远见", "选择", "决策"],
            analysis="是时候规划未来，选择前进的方向",
            affirmation="我清楚自己的目标，有勇气做出选择",
            type=TarotType.WANDS
        ),
        "24": TarotCard(
            id="24",
            name="权杖三",
            name_en="Three of Wands",
            image_url=f"{BASE_URL}wa03.jpg",
            description="象征远见、扩展、探索、商机",
            keywords=["远见", "扩展", "探索", "机遇"],
            analysis="扩展视野，寻找新的机会和可能",
            affirmation="我敞开天空，迎接新的可能",
            type=TarotType.WANDS
        ),
        "25": TarotCard(
            id="25",
            name="权杖四",
            name_en="Four of Wands",
            image_url=f"{BASE_URL}wa04.jpg",
            description="代表庆祝、和谐、稳定的基础",
            keywords=["庆祝", "和谐", "稳定", "成就"],
            analysis="值得庆祝的时刻，享受当下的和谐",
            affirmation="我感恩生活中的和谐与稳定",
            type=TarotType.WANDS
        ),
        "26": TarotCard(
            id="26",
            name="权杖五",
            name_en="Five of Wands",
            image_url=f"{BASE_URL}wa05.jpg",
            description="象征竞争、冲突、挑战",
            keywords=["竞争", "冲突", "挑战", "成长"],
            analysis="面对挑战和竞争，这是成长的机会",
            affirmation="我在挑战中学习和成长，变得更强大",
            type=TarotType.WANDS
        ),
        "27": TarotCard(
            id="27",
            name="权杖六",
            name_en="Six of Wands",
            image_url=f"{BASE_URL}wa06.jpg",
            description="代表胜利、认可、成功",
            keywords=["胜利", "认可", "成功", "自信"],
            analysis="努力得到回报，获得认可和成功",
            affirmation="我为自己的成就感到骄傲和喜悦",
            type=TarotType.WANDS
        ),
        "28": TarotCard(
            id="28",
            name="权杖七",
            name_en="Seven of Wands",
            image_url=f"{BASE_URL}wa07.jpg",
            description="象征防守、坚持、挑战",
            keywords=["防守", "坚持", "勇气", "决心"],
            analysis="坚持立场，勇敢面对挑战",
            affirmation="我有勇气和力量守护自己的立场",
            type=TarotType.WANDS
        ),
        "29": TarotCard(
            id="29",
            name="权杖八",
            name_en="Eight of Wands",
            image_url=f"{BASE_URL}wa08.jpg",
            description="代表快速行动、进展、消息",
            keywords=["速度", "行动", "进展", "消息"],
            analysis="事情快速发展，保持灵活应对",
            affirmation="我准备好迎接快速的变化和进展",
            type=TarotType.WANDS
        ),
        "30": TarotCard(
            id="30",
            name="权杖九",
            name_en="Nine of Wands",
            image_url=f"{BASE_URL}wa09.jpg",
            description="象征防备、坚持、最后的努力",
            keywords=["防备", "坚持", "韧性", "警惕"],
            analysis="保持警惕，坚持到最后一刻",
            affirmation="我有力量和韧性度过任何挑战",
            type=TarotType.WANDS
        ),
        "31": TarotCard(
            id="31",
            name="权杖十",
            name_en="Ten of Wands",
            image_url=f"{BASE_URL}wa10.jpg",
            description="代表负担、责任、压力",
            keywords=["负担", "责任", "压力", "坚持"],
            analysis="当前责任重大，需要适当调整和分配",
            affirmation="我有智慧处理压力，懂得寻求帮助",
            type=TarotType.WANDS
        ),
        "32": TarotCard(
            id="32",
            name="权杖侍从",
            name_en="Page of Wands",
            image_url=f"{BASE_URL}wapa.jpg",
            description="象征探索、热情、新消息",
            keywords=["探索", "热情", "学习", "冒险"],
            analysis="保持好奇和热情，探索新的可能",
            affirmation="我以热情和好奇探索生活",
            type=TarotType.WANDS
        ),
        "33": TarotCard(
            id="33",
            name="权杖骑士",
            name_en="Knight of Wands",
            image_url=f"{BASE_URL}wakn.jpg",
            description="代表冒险、行动、热情",
            keywords=["冒险", "行动", "热情", "进取"],
            analysis="是采取行动的时候，跟随内心的热情",
            affirmation="我充满热情地追求目标，勇往直前",
            type=TarotType.WANDS
        ),
        "34": TarotCard(
            id="34",
            name="权杖皇后",
            name_en="Queen of Wands",
            image_url=f"{BASE_URL}waqu.jpg",
            description="象征自信、魅力、创造力",
            keywords=["自信", "魅力", "创造", "领导"],
            analysis="展现自信和魅力，激发创造力",
            affirmation="我散发自信光芒，激励他人前行",
            type=TarotType.WANDS
        ),
        "35": TarotCard(
            id="35",
            name="权杖国王",
            name_en="King of Wands",
            image_url=f"{BASE_URL}waki.jpg",
            description="代表领导力、远见、创业精神",
            keywords=["领导", "远见", "创业", "魄力"],
            analysis="发挥领导才能，展现远见卓识",
            affirmation="我有能力引领他人，创造非凡成就",
            type=TarotType.WANDS
        ),
        # 圣杯组（36-49）
        "36": TarotCard(
            id="36",
            name="圣杯王牌",
            name_en="Ace of Cups",
            image_url=f"{BASE_URL}cupa.jpg",
            description="象征新的感情、灵感、直觉的开始",
            keywords=["感情", "直觉", "创意", "新生"],
            analysis="新的情感体验即将开始，保持心灵开放",
            affirmation="我的心灵充满爱与创造力",
            type=TarotType.CUPS
        ),
        "37": TarotCard(
            id="37",
            name="圣杯二",
            name_en="Two of Cups",
            image_url=f"{BASE_URL}cu02.jpg",
            description="代表伙伴关系、结合、和谐",
            keywords=["伙伴", "和谐", "结合", "相遇"],
            analysis="重要的关系正在形成，保持真诚相待",
            affirmation="我吸引并建立和谐的关系",
            type=TarotType.CUPS
        ),
        "38": TarotCard(
            id="38",
            name="圣杯三",
            name_en="Three of Cups",
            image_url=f"{BASE_URL}cu03.jpg",
            description="象征庆祝、友情、欢乐",
            keywords=["庆祝", "友情", "欢乐", "团聚"],
            analysis="与朋友共享快乐时光，享受团聚",
            affirmation="我享受与他人分享快乐的时光",
            type=TarotType.CUPS
        ),
        "39": TarotCard(
            id="39",
            name="圣杯四",
            name_en="Four of Cups",
            image_url=f"{BASE_URL}cu04.jpg",
            description="代表倦怠、不满、重新评估",
            keywords=["倦怠", "反思", "评估", "机会"],
            analysis="需要重新审视现状，发现被忽略的机会",
            affirmation="我愿意以新的视角查看生活",
            type=TarotType.CUPS
        ),
        "40": TarotCard(
            id="40",
            name="圣杯五",
            name_en="Five of Cups",
            image_url=f"{BASE_URL}cu05.jpg",
            description="象征失落、遗憾、治愈",
            keywords=["失落", "遗憾", "治愈", "希望"],
            analysis="关注仍然拥有的，而不是失去的",
            affirmation="我允许自己疗愈，并看见新的希望",
            type=TarotType.CUPS
        ),
        "41": TarotCard(
            id="41",
            name="圣杯六",
            name_en="Six of Cups",
            image_url=f"{BASE_URL}cu06.jpg",
            description="代表怀旧、纯真、回忆",
            keywords=["怀旧", "纯真", "回忆", "给予"],
            analysis="珍惜美好的回忆，保持纯真的心",
            affirmation="我感恩过去的美好，活在当下",
            type=TarotType.CUPS
        ),
        "42": TarotCard(
            id="42",
            name="圣杯七",
            name_en="Seven of Cups",
            image_url=f"{BASE_URL}cu07.jpg",
            description="象征幻想、选择、梦想",
            keywords=["幻想", "选择", "梦想", "现实"],
            analysis="面对多个选择，需要明确真实的愿望",
            affirmation="我能分辨真实与幻想，做出明智的选择",
            type=TarotType.CUPS
        ),
        "43": TarotCard(
            id="43",
            name="圣杯八",
            name_en="Eight of Cups",
            image_url=f"{BASE_URL}cu08.jpg",
            description="代表放下、寻找、转变",
            keywords=["放下", "寻找", "转变", "旅程"],
            analysis="是时候放下旧的，寻找更有意义的事物",
            affirmation="我勇于追寻内心真正的渴望",
            type=TarotType.CUPS
        ),
        "44": TarotCard(
            id="44",
            name="圣杯九",
            name_en="Nine of Cups",
            image_url=f"{BASE_URL}cu09.jpg",
            description="象征满足、愿望实现、幸福",
            keywords=["满足", "实现", "幸福", "满意"],
            analysis="愿望即将实现，享受当下的满足感",
            affirmation="我感恩生活中的一切美好",
            type=TarotType.CUPS
        ),
        "45": TarotCard(
            id="45",
            name="圣杯十",
            name_en="Ten of Cups",
            image_url=f"{BASE_URL}cu10.jpg",
            description="代表圆满、家庭幸福、和谐",
            keywords=["圆满", "家庭", "和谐", "幸福"],
            analysis="享受完美的家庭生活和情感满足",
            affirmation="我创造并享受圆满的人生",
            type=TarotType.CUPS
        ),
        "46": TarotCard(
            id="46",
            name="圣杯侍从",
            name_en="Page of Cups",
            image_url=f"{BASE_URL}cupa.jpg",
            description="象征感性、创意、好消息",
            keywords=["感性", "创意", "消息", "学习"],
            analysis="保持感性和创意，接收好消息",
            affirmation="我敞开心扉，接受爱与创意",
            type=TarotType.CUPS
        ),
        "47": TarotCard(
            id="47",
            name="圣杯骑士",
            name_en="Knight of Cups",
            image_url=f"{BASE_URL}cukn.jpg",
            description="代表浪漫、追求、提议",
            keywords=["浪漫", "追求", "提议", "行动"],
            analysis="追随内心的感受，采取浪漫行动",
            affirmation="我勇于表达真挚的情感",
            type=TarotType.CUPS
        ),
        "48": TarotCard(
            id="48",
            name="圣杯皇后",
            name_en="Queen of Cups",
            image_url=f"{BASE_URL}cuqu.jpg",
            description="象征同理心、关怀、直觉",
            keywords=["同理心", "关怀", "直觉", "温柔"],
            analysis="用温柔和同理心对待他人和自己",
            affirmation="我以爱与理解对待每个人",
            type=TarotType.CUPS
        ),
        "49": TarotCard(
            id="49",
            name="圣杯国王",
            name_en="King of Cups",
            image_url=f"{BASE_URL}cuki.jpg",
            description="代表情感智慧、平和、成熟",
            keywords=["智慧", "平和", "成熟", "控制"],
            analysis="以成熟的方式掌控情感",
            affirmation="我能平和地掌控自己的情感",
            type=TarotType.CUPS
        ),
        "50": TarotCard(
            id="50",
            name="宝剑王牌",
            name_en="Ace of Swords",
            image_url=f"{BASE_URL}swpa.jpg",
            description="象征突破、清晰、真理、胜利",
            keywords=["突破", "清晰", "真理", "洞察"],
            analysis="新的思维突破，获得清晰的洞察",
            affirmation="我拥有清晰的思维和洞察力",
            type=TarotType.SWORDS
        ),
        "51": TarotCard(
            id="51",
            name="宝剑二",
            name_en="Two of Swords",
            image_url=f"{BASE_URL}sw02.jpg",
            description="代表平衡、决策、僵局",
            keywords=["平衡", "决策", "僵局", "和解"],
            analysis="需要做出决定，打破当前的僵局",
            affirmation="我有勇气面对并做出明智的决定",
            type=TarotType.SWORDS
        ),
        "52": TarotCard(
            id="52",
            name="宝剑三",
            name_en="Three of Swords",
            image_url=f"{BASE_URL}sw03.jpg",
            description="象征心痛、失望、释放",
            keywords=["心痛", "失望", "释放", "成长"],
            analysis="接受并释放痛苦，这是成长的过程",
            affirmation="我允许自己感受并释放痛苦",
            type=TarotType.SWORDS
        ),
        "53": TarotCard(
            id="53",
            name="宝剑四",
            name_en="Four of Swords",
            image_url=f"{BASE_URL}sw04.jpg",
            description="代表休息、恢复、冥想",
            keywords=["休息", "恢复", "冥想", "平静"],
            analysis="需要适当的休息和恢复时间",
            affirmation="我给自己充分的时间休息和恢复",
            type=TarotType.SWORDS
        ),
        "54": TarotCard(
            id="54",
            name="宝剑五",
            name_en="Five of Swords",
            image_url=f"{BASE_URL}sw05.jpg",
            description="象征冲突、失败、教训",
            keywords=["冲突", "失败", "教训", "智慧"],
            analysis="从冲突中学习，获得智慧",
            affirmation="我从每次挫折中学习和成长",
            type=TarotType.SWORDS
        ),
        "55": TarotCard(
            id="55",
            name="宝剑六",
            name_en="Six of Swords",
            image_url=f"{BASE_URL}sw06.jpg",
            description="代表过渡、改变、疗愈",
            keywords=["过渡", "改变", "疗愈", "前进"],
            analysis="正在经历转变，朝着更好的方向前进",
            affirmation="我勇于改变，迎接新的开始",
            type=TarotType.SWORDS
        ),
        "56": TarotCard(
            id="56",
            name="宝剑七",
            name_en="Seven of Swords",
            image_url=f"{BASE_URL}sw07.jpg",
            description="象征策略、谨慎、独立",
            keywords=["策略", "谨慎", "独立", "智慧"],
            analysis="需要明智地运用策略，保持警觉",
            affirmation="我运用智慧做出最佳选择",
            type=TarotType.SWORDS
        ),
        "57": TarotCard(
            id="57",
            name="宝剑八",
            name_en="Eight of Swords",
            image_url=f"{BASE_URL}sw08.jpg",
            description="代表束缚、限制、自我设限",
            keywords=["束缚", "限制", "解放", "觉醒"],
            analysis="打破自我限制，获得内在自由",
            affirmation="我能够突破限制，获得自由",
            type=TarotType.SWORDS
        ),
        "58": TarotCard(
            id="58",
            name="宝剑九",
            name_en="Nine of Swords",
            image_url=f"{BASE_URL}sw09.jpg",
            description="象征忧虑、恐惧、噩梦",
            keywords=["忧虑", "恐惧", "觉醒", "释放"],
            analysis="面对并释放内心的恐惧和忧虑",
            affirmation="我释放恐惧，拥抱内心的平安",
            type=TarotType.SWORDS
        ),
        "59": TarotCard(
            id="59",
            name="宝剑十",
            name_en="Ten of Swords",
            image_url=f"{BASE_URL}sw10.jpg",
            description="代表结束、重生、转机",
            keywords=["结束", "重生", "转机", "希望"],
            analysis="最黑暗的时刻即将过去，黎明将至",
            affirmation="我相信每个结束都是新的开始",
            type=TarotType.SWORDS
        ),
        "60": TarotCard(
            id="60",
            name="宝剑侍从",
            name_en="Page of Swords",
            image_url=f"{BASE_URL}swpa.jpg",
            description="象征好奇、学习、观察",
            keywords=["好奇", "学习", "观察", "真理"],
            analysis="保持求知欲和敏锐的观察力",
            affirmation="我以好奇探索真理",
            type=TarotType.SWORDS
        ),
        "61": TarotCard(
            id="61",
            name="宝剑骑士",
            name_en="Knight of Swords",
            image_url=f"{BASE_URL}swkn.jpg",
            description="代表行动、果断、直接",
            keywords=["行动", "果断", "直接", "勇气"],
            analysis="果断采取行动，勇往直前",
            affirmation="我勇敢而果断地追求目标",
            type=TarotType.SWORDS
        ),
        "62": TarotCard(
            id="62",
            name="宝剑皇后",
            name_en="Queen of Swords",
            image_url=f"{BASE_URL}swqu.jpg",
            description="象征智慧、独立、清晰",
            keywords=["智慧", "独立", "清晰", "理性"],
            analysis="运用智慧和理性做出判断",
            affirmation="我以智慧和清晰的思维前行",
            type=TarotType.SWORDS
        ),
        "63": TarotCard(
            id="63",
            name="宝剑国王",
            name_en="King of Swords",
            image_url=f"{BASE_URL}swki.jpg",
            description="代表理性、权威、真理",
            keywords=["理性", "权威", "真理", "公正"],
            analysis="以理性和公正的态度处理事务",
            affirmation="我以理性和公正引导他人",
            type=TarotType.SWORDS
        ),
          "64": TarotCard(
            id="64",
            name="星币王牌",
            name_en="Ace of Pentacles",
            image_url=f"{BASE_URL}pepa.jpg",
            description="象征新机会、繁荣、物质起点",
            keywords=["机会", "繁荣", "起点", "实现"],
            analysis="新的物质机会即将到来，把握机遇",
            affirmation="我准备好接受丰盛的祝福",
            type=TarotType.PENTACLES
        ),
        "65": TarotCard(
            id="65",
            name="星币二",
            name_en="Two of Pentacles",
            image_url=f"{BASE_URL}pe02.jpg",
            description="代表平衡、适应、多任务",
            keywords=["平衡", "适应", "变通", "灵活"],
            analysis="保持灵活，在多重任务中找到平衡",
            affirmation="我能灵活应对生活的挑战",
            type=TarotType.PENTACLES
        ),
        "66": TarotCard(
            id="66",
            name="星币三",
            name_en="Three of Pentacles",
            image_url=f"{BASE_URL}pe03.jpg",
            description="象征合作、技能、认可",
            keywords=["合作", "技能", "认可", "成就"],
            analysis="通过合作实现目标，展现专业技能",
            affirmation="我的努力和才能得到认可",
            type=TarotType.PENTACLES
        ),
        "67": TarotCard(
            id="67",
            name="星币四",
            name_en="Four of Pentacles",
            image_url=f"{BASE_URL}pe04.jpg",
            description="代表保守、安全感、控制",
            keywords=["保守", "安全", "控制", "稳定"],
            analysis="需要在安全与开放之间找到平衡",
            affirmation="我在稳定中寻找成长的机会",
            type=TarotType.PENTACLES
        ),
        "68": TarotCard(
            id="68",
            name="星币五",
            name_en="Five of Pentacles",
            image_url=f"{BASE_URL}pe05.jpg",
            description="象征困难、匮乏、考验",
            keywords=["困难", "匮乏", "考验", "信心"],
            analysis="暂时的困难将过去，保持信心",
            affirmation="我相信困境中有转机和祝福",
            type=TarotType.PENTACLES
        ),
        "69": TarotCard(
            id="69",
            name="星币六",
            name_en="Six of Pentacles",
            image_url=f"{BASE_URL}pe06.jpg",
            description="代表慷慨、给予、接受",
            keywords=["慷慨", "给予", "接受", "平衡"],
            analysis="在给予和接受中找到平衡",
            affirmation="我在给予中获得丰盛",
            type=TarotType.PENTACLES
        ),
        "70": TarotCard(
            id="70",
            name="星币七",
            name_en="Seven of Pentacles",
            image_url=f"{BASE_URL}pe07.jpg",
            description="象征评估、耐心、投资",
            keywords=["评估", "耐心", "投资", "收获"],
            analysis="耐心等待努力的成果，评估进展",
            affirmation="我相信付出必有收获",
            type=TarotType.PENTACLES
        ),
        "71": TarotCard(
            id="71",
            name="星币八",
            name_en="Eight of Pentacles",
            image_url=f"{BASE_URL}pe08.jpg",
            description="代表专注、技艺、进步",
            keywords=["专注", "技艺", "进步", "精进"],
            analysis="通过专注和努力提升技能",
            affirmation="我在专注中不断提升自己",
            type=TarotType.PENTACLES
        ),
        "72": TarotCard(
            id="72",
            name="星币九",
            name_en="Nine of Pentacles",
            image_url=f"{BASE_URL}pe09.jpg",
            description="象征独立、成就、享受",
            keywords=["独立", "成就", "享受", "自律"],
            analysis="享受独立自主带来的成就感",
            affirmation="我享受努力带来的成果",
            type=TarotType.PENTACLES
        ),
        "73": TarotCard(
            id="73",
            name="星币十",
            name_en="Ten of Pentacles",
            image_url=f"{BASE_URL}pe10.jpg",
            description="代表富足、传承、安稳",
            keywords=["富足", "传承", "安稳", "圆满"],
            analysis="实现物质和精神的双重富足",
            affirmation="我创造持久的富足与幸福",
            type=TarotType.PENTACLES
        ),
        "74": TarotCard(
            id="74",
            name="星币侍从",
            name_en="Page of Pentacles",
            image_url=f"{BASE_URL}pepa.jpg",
            description="象征学习、实践、机会",
            keywords=["学习", "实践", "机会", "开始"],
            analysis="以务实的态度学习新技能",
            affirmation="我以开放的心学习新事物",
            type=TarotType.PENTACLES
        ),
        "75": TarotCard(
            id="75",
            name="星币骑士",
            name_en="Knight of Pentacles",
            image_url=f"{BASE_URL}pekn.jpg",
            description="代表责任、勤奋、踏实",
            keywords=["责任", "勤奋", "踏实", "坚持"],
            analysis="通过踏实的努力达成目标",
            affirmation="我以坚持不懈的态度追求目标",
            type=TarotType.PENTACLES
        ),
        "76": TarotCard(
            id="76",
            name="星币皇后",
            name_en="Queen of Pentacles",
            image_url=f"{BASE_URL}pequ.jpg",
            description="象征丰盛、实用、滋养",
            keywords=["丰盛", "实用", "滋养", "富足"],
            analysis="创造并享受物质与精神的富足",
            affirmation="我滋养自己和他人的生命",
            type=TarotType.PENTACLES
        ),
        "77": TarotCard(
            id="77",
            name="星币国王",
            name_en="King of Pentacles",
            image_url=f"{BASE_URL}peki.jpg",
            description="代表富有、稳健、实力",
            keywords=["富有", "稳健", "实力", "成功"],
            analysis="以稳健的方式实现物质成功",
            affirmation="我有能力创造持久的繁荣",
            type=TarotType.PENTACLES
        ),
    }

    @staticmethod
    async def get_random_cards(count: int = 4) -> List[TarotCard]:
        cards = list(TarotService.ALL_CARDS.values())
        return random.sample(cards, min(count, len(cards)))