version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/yubanai
      - WX_APPID=wx86ab8c9cb936067c  # 确保这里使用正确的APPID
      - WX_SECRET=fb90299a4f66bba528809f4f8f3065d8  # 确保这
    depends_on:
      - mongo
    networks:
      - yubanai-network
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - yubanai-network
    environment:
      - MONGO_INITDB_DATABASE=yubanai
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  yubanai-network:
    driver: bridge

volumes:
  mongo_data: